print("            =")
print("           ===")
print("          =====")
print("         === ===")
print("        ===   ===")
print("       ===     ===")
print("      ===       ===")
print("     ===============")
print("    =================")
print("   ===             ===")
print("  ===               ===")
print(" =======================")
print("=========================")

#I tired to rebuild the sign from my favourite band Thirty Seconds to Mars :) 
#(picture for refernce in the readme file). 
